"""
Django settings for HvacAppDjango project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import sqlite3
from pathlib import Path




# Build paths inside the project like this: BASE_DIR / 'subdir'.
from HvacAppDjango.JassminSettings import JAZZMIN_SETTINGS_DATA

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ml22s^77n%7+9@kh^!kg%13=%we)@0-=_73vz)yiscf05w3!+v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.2']
INTERNAL_IPS = ['127.0.0.2']


def custom_show_toolbar(request):
	return True  # Always show toolbar, for example purposes only.


INSTALLED_APPS = [
	'jazzmin',
	# "debug_toolbar",
	'import_export',
	'adminactions',
	'django.contrib.admin',
	'django_extensions',
	# "django_custom_admin_pages",
	# "django_custom_admin_pages.admin.CustomAdminConfig",
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'calculation',
	'admin_form_action',
	'StaticDB',
	'Config',
	'Spaces',
	'Structures',
	'Systems',
	'Terminals',
	'HeatBalance',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	# "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'HvacAppDjango.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates']
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'HvacAppDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # 'static_db': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'static_db.sqlite3',
    # }
}
# DATABASE_ROUTERS = ['StaticDB.DbRouter.StaticDataRouter',]
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JSON_SPACE_PATH = BASE_DIR / "polygon_data_file.json"

CONNECTION = sqlite3.connect(DATABASES['default']['NAME'])

JAZZMIN_SETTINGS = JAZZMIN_SETTINGS_DATA
LOGIN_REDIRECT_URL = '/'
