# Generated by Django 5.0.6 on 2024-06-18 11:36

import StaticDB.StaticData.SpaceDataRepresentation
import StaticDB.StaticData.StructureTypeData
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('R_real', models.FloatField(default=1, help_text='принимается в расчетах если не заданы слои конструкций', verbose_name='Факт.терм. сопр.')),
                ('standard_structure_type', models.CharField(choices=[('Wall', 'Стена'), ('Door', 'Дверь'), ('Window', 'Окно'), ('Skylight', 'Зенитный фонарь'), ('Floor', 'Перекрытие'), ('Roof', 'Кровля')], default=StaticDB.StaticData.StructureTypeData.StructureTypeData['Wall'], max_length=200, verbose_name='тип')),
                ('structure_picture', models.ImageField(blank=True, upload_to='StructureType/%Y/%m/%d/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '03 Базовая конструкция',
                'verbose_name_plural': '03 Базовые конструкции',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='крат.наим')),
                ('orientation', models.CharField(choices=[('ND', 'Нет данных'), ('N', 'С'), ('NE', 'СВ'), ('E', 'В'), ('SE', 'ЮВ'), ('S', 'Ю'), ('SW', 'ЮЗ'), ('W', 'З'), ('NW', 'СЗ')], default='ND', max_length=3, verbose_name='ориент.')),
                ('width', models.FloatField(blank=True, default=1, null=True, verbose_name='Ширина')),
                ('length', models.FloatField(blank=True, default=1, null=True, verbose_name='Длина')),
                ('quantity', models.FloatField(blank=True, default=1, null=True, verbose_name='Колличество конструкций')),
                ('area', models.FloatField(default=1, null=True, verbose_name='пл.констр.')),
                ('base_structures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_structure', to='Structures.basestructure', verbose_name='Базовая конструкция')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Spaces.spacedata', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Ограждающая конструкция',
                'verbose_name_plural': 'Ограждающие конструкции',
                'ordering': ['base_structures__name'],
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
    ]
