# Generated by Django 5.0.6 on 2024-06-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Config', '0001_initial'),
        ('StaticDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceData',
            fields=[
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('S_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('S_Number', models.IntegerField(blank=True, null=True)),
                ('S_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('S_height', models.FloatField(blank=True, null=True)),
                ('S_area', models.FloatField(blank=True, null=True)),
                ('S_Volume', models.FloatField(blank=True, null=True)),
                ('S_level', models.CharField(blank=True, max_length=200, null=True)),
                ('human_number', models.FloatField(blank=True, default=1, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Config.building')),
                ('space_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StaticDB.spacecategory')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
    ]
