# Generated by Django 5.0.6 on 2024-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_orientation_option1', models.CharField(choices=[('up', 'верх'), ('down', 'вниз'), ('left', 'лево'), ('right', 'вправо'), ('center_horizontal', 'центр горизонт.'), ('center_vertical', 'центр вертикал.')], default=('up', 'верх'), max_length=20)),
                ('device_orientation_option2', models.CharField(choices=[('up', 'верх'), ('down', 'вниз'), ('left', 'лево'), ('right', 'вправо'), ('center_horizontal', 'центр горизонт.'), ('center_vertical', 'центр вертикал.')], default=('up', 'верх'), max_length=20)),
                ('single_device_orientation', models.CharField(choices=[('corner', 'Угол'), ('center', 'Центр')], default=('corner', 'Угол'), max_length=20)),
                ('wall_offset', models.FloatField(default=500)),
                ('ceiling_offset', models.FloatField(default=500)),
            ],
            options={
                'verbose_name': 'Оборудование Геометрия',
            },
        ),
        migrations.CreateModel(
            name='EquipmentBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_equipment_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=200)),
                ('equipment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('family_device_name', models.CharField(max_length=200)),
                ('family_instance_name', models.CharField(max_length=200)),
                ('max_flow', models.FloatField()),
                ('normal_velocity', models.FloatField(blank=True, default=2, null=True)),
                ('geometry', models.CharField(max_length=200)),
                ('dimension1', models.CharField(max_length=200)),
                ('manufacture', models.CharField(max_length=200)),
                ('system_flow_parameter_name', models.CharField(max_length=200)),
                ('system_name_parameter', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Оборудование База',
                'verbose_name_plural': 'Оборудование База',
            },
        ),
    ]
