# Generated by Django 5.0.6 on 2024-06-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaticDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('category', models.CharField(choices=[('living', 'Жилые, гостиницы и общежития'), ('schools', 'Дошкольные образовательные организации, общеобразовательные организации, медицинские организации и интернаты'), ('public', 'Общественные, кроме указанных выше, административные и бытовые, за исключением помещений с влажным или мокрым режимом'), ('industrial', 'Производственные с сухим и нормальным режимами')], default='living', max_length=150, verbose_name='категория помещения')),
                ('building_temperature', models.FloatField(default=20, verbose_name='внутренняя температура °С')),
                ('heated_volume', models.FloatField(default=34229, verbose_name='отапливаемый объем м3')),
                ('level_number', models.IntegerField(default=20, verbose_name='количество этажей')),
                ('level_height', models.FloatField(default=3, verbose_name='высота этажа,м')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('climate_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StaticDB.climatedata', verbose_name='климат.данные')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
    ]
