# Generated by Django 5.0.6 on 2024-06-18 11:36

import StaticDB.StaticData.SpaceDataRepresentation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Компьютер', max_length=200, verbose_name='Оборудование')),
                ('heat_load', models.FloatField(default=300, max_length=200, verbose_name='Мощность,Вт')),
            ],
            options={
                'verbose_name': 'База Оборудования',
                'verbose_name_plural': 'База Оборудования',
            },
        ),
        migrations.CreateModel(
            name='AirBalance',
            fields=[
            ],
            options={
                'verbose_name': 'Воздушный баланс',
                'verbose_name_plural': 'Воздушный баланс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Spaces.spacedata',),
        ),
        migrations.CreateModel(
            name='TotalHeat',
            fields=[
            ],
            options={
                'verbose_name': 'Тепловой баланс',
                'verbose_name_plural': 'Тепловой баланс',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Spaces.spacedata',),
        ),
        migrations.CreateModel(
            name='HeatAdditionalLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_load', models.FloatField(blank=True, null=True, verbose_name='дополнительные теплопотери')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.spacedata', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Доп. Тепловыделение',
                'verbose_name_plural': 'Доп. Тепловыделения',
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
        migrations.CreateModel(
            name='HeatLoadEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во')),
                ('heat_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeatBalance.heatequipment', verbose_name='Наим.обор.')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spaces.spacedata', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Тепловыделение Оборудование',
                'verbose_name_plural': 'Тепловыделение Оборудование',
                'ordering': ['space'],
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
        migrations.AddConstraint(
            model_name='heatloadequipment',
            constraint=models.UniqueConstraint(fields=('space', 'heat_equipment'), name='unique_load'),
        ),
    ]
