# Generated by Django 5.0.6 on 2024-06-18 11:36

import StaticDB.StaticData.SpaceDataRepresentation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Spaces', '0001_initial'),
        ('Terminals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=200)),
                ('system_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Система Наименование',
                'verbose_name_plural': 'Система Наименование',
            },
        ),
        migrations.CreateModel(
            name='SupplySystem',
            fields=[
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=20)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Spaces.spacedata')),
                ('calculation_options', models.CharField(choices=[('minimum_terminals', 'расчетный минимум'), ('directive_terminals', 'заданное колличество'), ('directive_length', 'заданная длина'), ('device_area', 'заданная площадь')], default=('minimum_terminals', 'расчетный минимум'), max_length=20)),
                ('family_device_name', models.CharField(max_length=200)),
                ('system_flow', models.FloatField(blank=True, default=0, null=True)),
                ('device_area', models.FloatField(blank=True, null=True)),
                ('directive_terminals', models.FloatField(blank=True, null=True)),
                ('directive_length', models.FloatField(blank=True, null=True)),
                ('geometry_options_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Terminals.devicegeometry')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Systems.systemname')),
            ],
            options={
                'verbose_name': 'Система Приточная',
                'verbose_name_plural': 'Система Приточная',
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
        migrations.CreateModel(
            name='HeatSystem',
            fields=[
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=20)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Spaces.spacedata')),
                ('calculation_options', models.CharField(choices=[('minimum_terminals', 'расчетный минимум'), ('directive_terminals', 'заданное колличество'), ('directive_length', 'заданная длина'), ('device_area', 'заданная площадь')], default=('minimum_terminals', 'расчетный минимум'), max_length=20)),
                ('family_device_name', models.CharField(max_length=200)),
                ('system_flow', models.FloatField(blank=True, default=0, null=True)),
                ('device_area', models.FloatField(blank=True, null=True)),
                ('directive_terminals', models.FloatField(blank=True, null=True)),
                ('directive_length', models.FloatField(blank=True, null=True)),
                ('geometry_options_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Terminals.devicegeometry')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Systems.systemname')),
            ],
            options={
                'verbose_name': 'Система Отопление',
                'verbose_name_plural': 'Система Отопление',
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
        migrations.CreateModel(
            name='FancoilSystem',
            fields=[
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=20)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Spaces.spacedata')),
                ('calculation_options', models.CharField(choices=[('minimum_terminals', 'расчетный минимум'), ('directive_terminals', 'заданное колличество'), ('directive_length', 'заданная длина'), ('device_area', 'заданная площадь')], default=('minimum_terminals', 'расчетный минимум'), max_length=20)),
                ('family_device_name', models.CharField(max_length=200)),
                ('system_flow', models.FloatField(blank=True, default=0, null=True)),
                ('device_area', models.FloatField(blank=True, null=True)),
                ('directive_terminals', models.FloatField(blank=True, null=True)),
                ('directive_length', models.FloatField(blank=True, null=True)),
                ('geometry_options_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Terminals.devicegeometry')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Systems.systemname')),
            ],
            options={
                'verbose_name': 'Система Кондиционирование',
                'verbose_name_plural': 'Система Кондиционирование',
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
        migrations.CreateModel(
            name='ExhaustSystem',
            fields=[
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('system_type', models.CharField(choices=[('Supply_system', 'Приточная'), ('Exhaust_system', 'Вытяжная'), ('Fan_coil_system', 'Кондиционирование'), ('Heat_system', 'Отопление')], default=('Supply_system', 'Приточная'), max_length=20)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Spaces.spacedata')),
                ('calculation_options', models.CharField(choices=[('minimum_terminals', 'расчетный минимум'), ('directive_terminals', 'заданное колличество'), ('directive_length', 'заданная длина'), ('device_area', 'заданная площадь')], default=('minimum_terminals', 'расчетный минимум'), max_length=20)),
                ('family_device_name', models.CharField(max_length=200)),
                ('system_flow', models.FloatField(blank=True, default=0, null=True)),
                ('device_area', models.FloatField(blank=True, null=True)),
                ('directive_terminals', models.FloatField(blank=True, null=True)),
                ('directive_length', models.FloatField(blank=True, null=True)),
                ('geometry_options_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Terminals.devicegeometry')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Systems.systemname')),
            ],
            options={
                'verbose_name': 'Система Вытяжная',
                'verbose_name_plural': 'Система Вытяжная',
            },
            bases=(models.Model, StaticDB.StaticData.SpaceDataRepresentation.SpaceDataRepresentation),
        ),
    ]
