# Generated by Django 5.0.6 on 2024-06-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Офис', max_length=200, verbose_name='Категория')),
                ('lighting', models.FloatField(default=20, verbose_name='Освещ. Вт/м2')),
                ('human_heat', models.FloatField(default=150, verbose_name='Люди. Вт/чел')),
                ('area_for_person', models.FloatField(default=7, verbose_name='Пл.на чел м2/чел')),
                ('min_temp', models.FloatField(default=18, verbose_name='Мин.темп. С')),
                ('max_temp', models.FloatField(default=22, verbose_name='Макс.темп. С')),
                ('phi_min', models.FloatField(default=40, verbose_name='Мин.влаж. %')),
                ('phi_max', models.FloatField(default=60, verbose_name='Макс.влаж. %')),
                ('Sup_air_mult', models.FloatField(default=2, verbose_name='Крат.приток')),
                ('Ex_air_mult', models.FloatField(default=2, verbose_name='Крат.вытяжка')),
                ('sup_air_human', models.FloatField(default=60, verbose_name='Гигиен.треб. м3/чел')),
                ('fresh_air', models.FloatField(default=0.8, verbose_name='процент свеж. возд.')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Категория Помещения',
                'verbose_name_plural': 'Категории Помещений',
            },
        ),
        migrations.CreateModel(
            name='SunRadiationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Москва', max_length=200, verbose_name='Наименование')),
                ('N', models.FloatField(default=100, verbose_name='С')),
                ('S', models.FloatField(default=360, verbose_name='Ю')),
                ('E', models.FloatField(default=350, verbose_name='В')),
                ('W', models.FloatField(default=350, verbose_name='З')),
                ('NW', models.FloatField(default=350, verbose_name='СЗ')),
                ('NE', models.FloatField(default=350, verbose_name='СВ')),
                ('SE', models.FloatField(default=350, verbose_name='ЮВ')),
                ('SW', models.FloatField(default=350, verbose_name='ЮЗ')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Солнечная радиация',
                'verbose_name_plural': 'Солнечная радиация',
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Москва', max_length=15, verbose_name='Город')),
                ('t_out_max', models.FloatField(default=-26, help_text='Температура холодной пятидневки с обеспеченностью 0.92', verbose_name='Расчетная температура наружного воздуха °С')),
                ('z_ot', models.FloatField(default=204, help_text='Продолжительность отопительного периода', verbose_name='Продолжительность отопительного периода, сут')),
                ('t_ot_middle', models.FloatField(default=-2.2, help_text='Средняя температура воздуха отопительного периода °С', verbose_name='Средняя температура воздуха отопительного периода')),
                ('air_velocity_middle', models.FloatField(default=3.8, verbose_name='средняя скорость наружного воздуха м/с')),
                ('air_velocity_max', models.FloatField(default=3.8, verbose_name='максимальная скорость наружного воздуха м/с')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('sun_radiation', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StaticDB.sunradiationdata', verbose_name='Солнечная радиация')),
            ],
            options={
                'verbose_name': 'Климатические данные',
                'verbose_name_plural': 'Климатические данные',
            },
        ),
    ]
